### ISSUE TITLE
[Maven]No shaded elements included in tikv-client-0.1.0-SNAPSHOT-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by Novemser** [pingcap/tikv-client-java#121]
It seems ```tikv-client-0.1.0-SNAPSHOT-jar-with-dependencies.jar```  doesn't proceed the shade procedure as expected, resulting in no shaded class files found in final jar.

**Comment by zhexuany** [comment]
Wired. Any specific details? Maven has sharded plugin. It should take care of everything.

**Comment by zhexuany** [comment]
Confirmed, but it is default behavior of `maven-assembly-plugin`. `tikv-client-0.1.0-SNAPSHOT-jar-with-dependencies.jar` is generated by `assembly-plugin`. I quote from original website "maven-assembly-plugin: This plugin extracts all dependency jars into raw classes, and group it together. It works in project with less dependencies only, for large project with many dependencies, it will cause Java class name conflict issue."

shaded packages can be found in `tikv-client-0.1.0-SNAPSHOT.jar`. Please use the following command to confirm:
`jar -tf target/tikv-client-0.1.0-SNAPSHOT.jar | grep 4pingcap`

**Comment by Novemser** [comment]
@zhexuany Thanks for your reply. :+1:
