### ISSUE TITLE
README is super out of date. Need update when double index read is merged. 

### ISSUE THREAD

**Issue by zhexuany** [pingcap/tikv-client-java#130]

**Comment by ilovesoup** [comment]
If intended to be used outside tispark, likely we need a API ref instead of simple README. I'd prefer for now we make README simple, and add more in API doc style later at least after DAG merged. What do you guys think?

**Comment by zhexuany** [comment]
Totally agree. README need to be simple and concise. Regarding of examples stuff, we need maintain a examples folder which allow user find user case over there.
