### ISSUE TITLE
datetime value has inconsistent timezone

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tikv-client-java#133]
Example:
```
mysql> select c15 from t1;
+---------------------+
| c15                 |
+---------------------+
| 2004-01-02 13:00:00 |
| 2004-01-02 13:00:00 |
+---------------------+
2 rows in set (0.00 sec)
```

While Spark read `datetime` with `+8` timezone.

```
scala> spark.sql("select c15 from t1").show(truncate=false)
+---------------------+
|c15                  |
+---------------------+
|2004-01-02 21:00:00.0|
|2004-01-02 21:00:00.0|
+---------------------+
```

I think we should bypass timezone's influence by getting more information from spark session.

**Comment by ilovesoup** [comment]
Since one of the user triggered this bug, move it to P0 and to be fixed right away.

**Comment by birdstorm** [comment]
In short, `datetime` is encoded WITH `timezone` in MySQL and TiDB, e.g., `2000-01-01 00:00:00` will be encoded into `2000-01-01 00:00:00 UTC+8` if its `timezone` is `UTC+8`.

In Spark, `datetime` type and `timestamp` type in mysql are converted to the same `Timestamp` type. 

The problem occurs when we read the `datetime` from jdbc, it is converted and displayed with local `timezone`. However, `datetime` has no sense of `timezone`, thus produced a `+8` timezone shift.

For now I am working on its actual cause and possible solution. Some issues addressed [here](https://hibernate.atlassian.net/browse/HHH-11396) and [here](https://stackoverflow.com/questions/9202857/timezones-in-sql-date-vs-java-sql-date) may be helpful. AFAIK raw Spark displays the correct answer.

So we should also check if `date` type has the same problem because they are treated the same in encoding and decoding. We may switch local timezone to negative to see if there will be any difference (`UTC +8` would not affect date display because the trailing time information is discarded).

Datatypes involving timezone are tricky, so this issue should be further discussed. @zhexuany @ilovesoup
