### ISSUE TITLE
Inconsistent result compared to TiDB on char type column

### ISSUE THREAD

**Issue by Novemser** [pingcap/tikv-client-java#140]
SQL:
```sql
select  count(1)  from full_data_type_table  where tp_char < 1
```
Result in TiSpark:
```sql
+--------+
|count(1)|
+--------+
|       0|
+--------+
```
Result in TiDB:
```sql
+----------+
| count(1) |
+----------+
|     1702 |
+----------+
```
Spark plan:
```shell
Project
+- Filter (isnotnull(tp_char#17) && (cast(tp_char#17 as double) < 1.0))
```
Note that spark cast `tp_char` to `double` type which may cause inconsistency with TiDB.

Some example data(All are pure random characters):
```sql
+------------+
| tp_char    |
+------------+
| uGL4TNrMeL |
| MsdqeUwUlS |
| vBgE4TuznW |
| slXDTtKsV3 |
| 9YhhBZYFW4 |
+------------+
```

**Comment by Novemser** [comment]
Result in MySQL client connected to MySQL Server version 5.7.19:
```sql
+----------+
| count(1) |
+----------+
|     1702 |
+----------+
```
Result in Spark with JDBC connected to MySQL Server version 5.7.19:
```sql
+--------+
|count(1)|
+--------+
|       0|
+--------+
```

**Comment by ilovesoup** [comment]
Please confirm since it looks like spark default behavior. @Novemser If so, close this issue please.

**Comment by Novemser** [comment]
The above case really is spark default behavior. Since casting `char` to `double` in `Spark SQL` is done by matching longest numeric prefix, some `char` may be cast to `null` if it's prefix doesn't contain any digital number, resulting in count zero rows as above case. @ilovesoup
