### ISSUE TITLE
Proto3 update breaks master build

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tikv-client-java#152]
This should be fix right now.

**Comment by Novemser** [comment]
Fix on this issue is [here](https://github.com/pingcap/tikv-client-lib-java/pull/153).

**Comment by ilovesoup** [comment]
Temp fix by pin to old commit of proto since it's compatible.  https://github.com/pingcap/tikv-client-lib-java/pull/153
Close this when all modify made.

**Comment by Novemser** [comment]
New fix adapted some code to support protobuf3. [#154](https://github.com/pingcap/tikv-client-lib-java/pull/154)

**Comment by birdstorm** [comment]
Should we close this issue since #154 has been merged?
