### ISSUE TITLE
Upgrade to GRPC 1.7

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tikv-client-java#155]
It seems lots of bug fixes has been made since 1.4.
We might need to upgrade Grpc considering it's pretty new project. Thorough test needed for upgrade.

**Comment by zhexuany** [comment]
this should be resolved by https://github.com/pingcap/tikv-client-lib-java/pull/157

**Comment by zhexuany** [comment]
For bazel, it is already fixed in its upstream. https://github.com/pubref/rules_protobuf/pull/150
