### ISSUE TITLE
Finish floating points types.

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tikv-client-java#16]
Please refer to https://dev.mysql.com/doc/refman/5.7/en/floating-point-types.html and keep the same behavior of TiDB's current implementation.

**Comment by zhexuany** [comment]
Well. Decimal type took me so much time. It is almost finished in `finish-coprocessor`.

**Comment by zhexuany** [comment]
This issue is related with https://github.com/pingcap/tikv-client-java/pull/33

**Comment by zhexuany** [comment]
PR just merges into master. Closing it.
