### ISSUE TITLE
Invalid Flag type for TimestampType: 7

### ISSUE THREAD

**Issue by Novemser** [pingcap/tikv-client-java#171]
Known affected branch:
```
master
DAGRequestConstruct
```

SQL
```sql
select  distinct(tp_time)  from full_data_type_table  order by tp_time
```

Exception
```java
Job aborted due to stage failure: Task 0 in stage 4301.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4301.0 (TID 4882, localhost, executor driver): com.pingcap.tikv.codec.InvalidCodecFormatException: Invalid Flag type for TimestampType: 7
	at com.pingcap.tikv.types.TimestampType.decodeNotNull(TimestampType.java:55)
	at com.pingcap.tikv.types.DataType.decodeValueToRow(DataType.java:133)
...ignored stack trace
```

Seems `time` type has not been decoded properly.

**Comment by ilovesoup** [comment]
Does this related to time type not supported problem?

**Comment by Novemser** [comment]
Will verify this with @birdstorm soon.

**Comment by Novemser** [comment]
If we don't push down `time` type, the same SQL will cause `Invalid Flag type for TimestampType: 8`, which is related to `time` type not supported in spark issue.

**Comment by birdstorm** [comment]
I believe they are all related to `flag type changed when pushed down` issue. Maybe we could merge them into one after verifying?

**Comment by birdstorm** [comment]
This issue will not occur since [this merged pull request](https://github.com/pingcap/tispark/pull/105), but potential problem still exists before issue #123 is resolved.

Closing.
