### ISSUE TITLE
Unexpected scan plan filter

### ISSUE THREAD

**Issue by Novemser** [pingcap/tikv-client-java#194]
After we push down `TiConstant` of date type
Scan builder with Index double read option open occurs some unexpected result.

SQL:
```sql
select l_shipdate from lineitem where l_shipdate < date '1998-09-02
```

Index double read open:
```sql
== Physical Plan ==
TiDB CoprocessorRDD{[table: lineitem] , Ranges: Start:[2], End: [2], Columns: [l_shipdate], Filter: Not(IsNull([l_shipdate]))}
```

Closed:
```sql
== Physical Plan ==
TiDB CoprocessorRDD{[table: lineitem] , Ranges: Start:[-9223372036854775808], End: [9223372036854775807], Columns: [l_shipdate], Filter: Not(IsNull([l_shipdate])), LessThan([l_shipdate], 1998-09-02)}
```

Don't sure with index double read open can we get correct result.

**Comment by Novemser** [comment]
Seems I forgot to print out index info.

**Comment by ilovesoup** [comment]
@Novemser I had a fix for index explain part already. https://github.com/pingcap/tikv-client-lib-java/pull/192
You can just review it.
