### ISSUE TITLE
Finish String type

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tikv-client-java#5]
Currently only Long type is mapped. Need string types of char and varchar.
Please refer to TiDB's codec and field_type for implementation.

**Comment by zhexuany** [comment]
We decided track types with issues. This is just for String type. It is done.

**Comment by zhexuany** [comment]
@ilovesoup anything to add?

**Comment by zhexuany** [comment]
This was done in https://github.com/pingcap/tikv-client-java/pull/12. Closing it.
