### ISSUE TITLE
Index support

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tikv-client-java#8]
It will be a relatively big task.
We might take a look at (executor/distsql.go) to see how to handle it properly.
Discussion needed for design.

**Comment by zhexuany** [comment]
Double Index is done. The PR was created since it was against to `dev_master` instead of `master`. I will resolve the conflict and create another PR in a day or two.

**Comment by zhexuany** [comment]
@birdstorm Please close this issue once you finish index

**Comment by birdstorm** [comment]
ok, working on it.

**Comment by ilovesoup** [comment]
I will close this first. Histogram is tracking by 
https://github.com/pingcap/tispark/issues/18
and
https://github.com/pingcap/tispark/issues/20
