### ISSUE TITLE
this project not support java1.8 when build it 

### ISSUE THREAD

**Issue by ouyangshourui** [pingcap/tikv-client-java#9]
the build log as following:

localhost:tikv-client-java ouyangshourui$ mvn package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.pingcap.tikv:tikv-client:jar:0.1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.powermock:powermock-module-junit4:jar -> duplicate declaration of version 1.6.6 @ line 61, column 21
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.fasterxml.jackson.core:jackson-databind:jar -> version 2.6.5 vs 2.6.6 @ line 84, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.classifier: osx-x86_64
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building tikv-client 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- protobuf-maven-plugin:0.5.0:compile (default) @ tikv-client ---
[INFO] Compiling 15 proto file(s) to /Users/ouyangshourui/GitHub/tikv-client-java/target/generated-sources/protobuf/java
[INFO] 
[INFO] --- protobuf-maven-plugin:0.5.0:compile-custom (default) @ tikv-client ---
[INFO] Compiling 15 proto file(s) to /Users/ouyangshourui/GitHub/tikv-client-java/target/generated-sources/protobuf/grpc-java
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ tikv-client ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/ouyangshourui/GitHub/tikv-client-java/src/main/resources
[INFO] Copying 15 resources
[INFO] Copying 15 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ tikv-client ---
[INFO] Compiling 106 source files to /Users/ouyangshourui/GitHub/tikv-client-java/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac, but could not parse the error:
javac: ????????: 1.8
??: javac <options> <source files>
-help ?????????

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.112 s
[INFO] Finished at: 2017-04-28T11:36:25+08:00
[INFO] Final Memory: 12M/222M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project tikv-client: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] javac: ????????: 1.8
[ERROR] ??: javac <options> <source files>
[ERROR] -help ?????????
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
localhost:tikv-client-java ouyangshourui$

**Comment by zhexuany** [comment]
@ouyangshourui Could you provide more specific env info?

**Comment by ouyangshourui** [comment]
@zhexuany   when jdk version 1.8.0 ,build will failure

**Comment by zhexuany** [comment]
@ouyangshourui 
My env is the following 
~~~
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
~~~

`mvn install` builds normally.

**Comment by ouyangshourui** [comment]
sorry, java version in my env has problem！thanks

**Comment by luyee** [comment]
必须jdk1.8?

**Comment by ilovesoup** [comment]
yes. It has to be jdk 1.8 since some lambda usage. 
是的，只能是1.8 里面用了不少lambda和一些1.8的特性.
